# .goreleaser.yml
# Build customization
builds:
  - binary: homebrew-ebscan
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
    - .elasticbeanstalk/*

brew:
  # Name of the recipe
  # Default to project name
  name: homebrew-ebscan

  # Reporitory to push the tap to.
  github:
    owner: pismo
    name: homebrew-ebscan

  # Allows you to set a custom download strategy.
  # Default is empty.
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: andriosr
    email: andriosr@gmail.com

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Caveats for the user of your binary.
  # Default is empty.
  caveats: "homebrew-ebscan -contains `substring-in-env-var`"

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/pismo/homebrew-ebscan/"

  # Your app's description.
  # Default is empty.
  description: "manipulates Elasticbeanstalk environmnet variables for all environments at once."

  # Setting this will prevent goreleaser to actually try to commit the updated
  # formula - instead, the formula file will be stored on the dist folder only,
  # leaving the responsibility of publishing it to the user.
  # Default is false.
  skip_upload: false

  # Packages your package depends on.
  dependencies:
    - awsebcli